### PR TITLE
sepolicy: Allow power hal to write to sysfs

### PR DESCRIPTION
**Pull request by derfelot**
Needed for DT2W.

### CODE REVIEW

**Comment by derfelot** [comment]
Fixed typo in commit message.

**Comment by cryptomilk** [comment]
You should define a `sysfs_touchpad` in `sepolicy/vendor/file.te` then label the sysfs path correctly in `sepolicy/vendor/genfs_contexts` and then give it permissions :-)

**Comment by derfelot** [comment]
I had a feeling you were going to say that :p

**Comment by derfelot** [comment]
For NFC, I think you changed this from my initial PR (https://github.com/cryptomilk/android_device_sony_common-treble/pull/16/commits/1c4a60c0090ffc14315c684c70ae8e57ea4caae3) . I tested this and for _whatever_ reason (I don't understand it anyway) we need both permissions. 

As it is now, nfaStorage.bin1 is not in data/vendor/nfc on a clean flash and NFC doesn't work (it fails silently actually, no denials triggered). With this chzange, everything is fine on a clean flash.

**Pull request merged**
